name: SSD CLI Flow Pushing the events

on:
  push:
    branches:
      - cli

    paths:
      - 'README.md'

jobs:
  build:
    uses: ORGANISATION/REPOSITORYNAME/.github/workflows/cli.yml@cli
    with:
      image_tag: ${{ github.run_id }}
      registry: 'REGISTRY URL'
      project: 'PROJECT NAME'
      repository: 'REPOSITORY'
      org: "ORGANISATION NAME"
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      SSD_URL: ${{ secrets.SSD_URL }}
      SSD_TEAM_TOKEN: ${{ secrets.SSD_TEAM_TOKEN }}
