apiVersion: v1
data:
  ssd-integrations.yaml: |
    jiraPollingInterval: 5
    integrationData:
      - stage: Source
        integrations:
          - integratorType: gitlab
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              token:
                encrypt: true
          - integratorType: github
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              token:
                encrypt: true
          - integratorType: bitbucket
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              token:
                encrypt: true
              username:
                encrypt: false
              password:
                encrypt: true
              workspaceId:
                encrypt: false
              projectKey:
                encrypt: false
              repository:
                encrypt: false
            featureConfigs:
              bitbucketAuthMode:
                default: bearer
              accessLevel:
                default: Workspace
          - integratorType: sonarqube
            category: scanningtool
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              token:
                encrypt: true
            featureConfigs:
              sonarqubeFileInsertion:
                default: inactive
          - integratorType: openssf
            category: scanningtool
            multiaccount: false
            featureConfigs:
              openssfcompliancescan:
                default: active
          - integratorType: virustotal
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              token:
                encrypt: true
            featureConfigs:
              urlScan:
                default: inactive
              malwareDetection:
                default: inactive
          - integratorType: snyk
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              snykOrgId:
                encrypt: false
              token:
                encrypt: true
              url:
                encrypt: false
            featureConfigs:
              sastsnykscan:
                default: Local Mode
              helmscan:
                default: inactive
          - integratorType: semgrep
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              token:
                encrypt: true
            featureConfigs:
              sastsemgrepscan:
                default: Local Mode
          - integratorType: codacy
            category: sourcetool
            multiaccount: false
            integratorConfigs:
              token:
                encrypt: true
            featureConfigs:
              sastcodacyscan:
                default: Local Mode
      - stage: Build
        integrations:
          - integratorType: jenkins
            category: citool
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              approved_user:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
      - stage: Artifact
        integrations:
          - integratorType: trivy
            category: scanningtool
            multiaccount: false
            featureConfigs:
              vulnerabilityscan:
                default: active
              helmscan:
                default: active
              secretscanforsource:
                default: active
              secretscanforcontainers:
                default: active
              licensescanforsource:
                default: active
              licensescanforcontainers:
                default: active
          - integratorType: docker
            category: dockerregistry
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              repo:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
          - integratorType: acr
            category: dockerregistry
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              repo:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
          - integratorType: gcr
            category: dockerregistry
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              fileName:
                encrypt: false
              fileData:
                encrypt: true
          - integratorType: ecr
            category: dockerregistry
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              repo:
                encrypt: false
              region:
                encrypt: false
              awsAccessKey:
                encrypt: true
              awsSecretKey:
                encrypt: true
          - integratorType: quay
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              repo:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
          - integratorType: jfrog
            category: dockerregistry
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              repo:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
          - integratorType: jfrogartifactory
            category: dockerregistry
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              username:
                encrypt: false
              token:
                encrypt: true
          - integratorType: jfrogxray
            category: getsbom
            multiaccount: true
            integratorConfigs:
              url:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
          - integratorType: google-artifact-registry
            category: aptregistry
            multiaccount: false
            integratorConfigs:
              key:
                encrypt: true
              source:
                encrypt: false
          - integratorType: grype
            category: scanningtool
            multiaccount: false
            featureConfigs:
              vulnerabilityscan:
                default: inactive
          - integratorType: syft
            category: scanningtool
            multiaccount: false
            featureConfigs:
              vulnerabilityscan:
                default: inactive
      - stage: Others
        integrations:
          - integratorType: chatgpt
            category: communications
            multiaccount: false
            integratorConfigs:
              token:
                encrypt: true
          - integratorType: slack
            category: communications
            multiaccount: false
            integratorConfigs:
              channel:
                encrypt: false
              token:
                encrypt: true
          - integratorType: jira
            category: communications
            multiaccount: false
            integratorConfigs:
              projectKey:
                encrypt: false
              username:
                encrypt: false
              url:
                encrypt: false
              token:
                encrypt: true
              field:
                encrypt: false
              value:
                encrypt: false
              assignJiraToOwner:
                encrypt: false
              todo:
                encrypt: false
              inprogress:
                encrypt: false
              done:
                encrypt: false
              wontdo:
                encrypt: false
            featureConfigs:
              mode:
                default: cloud
              jiraTicketTriggerType:
                default: deduplications
              jiraTicketCreationScope:
                default: vulnerability_policies
          - integratorType: custompolicy
            category: managementtool
            multiaccount: false
            integratorConfigs:
              url:
                encrypt: false
              token:
                encrypt: true
          - integratorType: mobsf
            category: scanningtool
            multiaccount: false
            featureConfigs:
              staticScan:
                default: inactive
              dynamicScan:
                default: inactive
          - integratorType: tfsec
            category: communications
            multiaccount: false
            integratorConfigs:
              name:
                encrypt: false
              url:
                encrypt: false
              token:
                encrypt: true
              branch:
                encrypt: false
              scriptabsolutepath:
                encrypt: false
              application:
                encrypt: false
      - stage: Post Deploy
        integrations:
          - integratorType: zap
            category: scanningtool
            multiaccount: true
            integratorConfigs:
              serviceUrl:
                encrypt: false
              username:
                encrypt: false
              password:
                encrypt: true
              retries:
                encrypt: false
              threshold:
                encrypt: false
              delay:
                encrypt: false
              account:
                encrypt: false
              appName:
                encrypt: false
              serviceName:
                encrypt: false
              excludeUrls:
                encrypt: false
              loginUrl:
                encrypt: false
              usernameField:
                encrypt: false
              passwordField:
                encrypt: false
              loginIndicator:
                encrypt: false
              logoutIndicator:
                encrypt: false
      - stage: Cloud Security Provider
        integrations:
          - integratorType: aws
            category: cloudsecuritytool
            multiaccount: true
            integratorConfigs:
              awsAccessKey:
                encrypt: true
              awsSecretKey:
                encrypt: true
      - stage: Cloud Security Posture Management
        integrations:
          - integratorType: scoutsuite
            category: scanningtool
            multiaccount: false
            featureConfigs:
              cspmscan:
                default: inactive
    
kind: ConfigMap
metadata:
  name: supplychain-api-cm
  labels:
    app: ssd
    component: supplychain-api
    heritage: "Helm"
    release: "ssd"
    chart: "ssd-2025.01.00"
