apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-job
data:
  upgrade-job.yaml: |
    prodGraphQLAddr: http://dgraph-public:8080
    upgradeFromVersion: April2025
    upgradeToVersion: June2025
