apiVersion: v1
kind: ConfigMap
metadata:
  name: project
data:
  project.yaml: |
    - name: docker-ss-9
      scanType: artifactScan
      platform: docker
      accountId: '0x2a69'
      teamId: ''
      scanLevel: repoLevel
      organisation: opsmx11
      type: ''
      projectConfigs:
        - repository: tcollector
          scheduleTime: 0
          tag:
            - latest
          tagPattern: ''
          scanUpto: 0
