apiVersion: v1
kind: ConfigMap
metadata:
  name: adhoc-project-cm
data:
  project.yaml: |
    - name: org-level-github-project
      scanType: sourceScan
      platform: github
      accountName: test-gh
      teamId: ''
      scanLevel: repoLevel
      organisation: AswathyAsokan-opsmx
      type: user
      projectConfigs:
        - repository: snyk-test
          scheduleTime: 0
          branch:
            - onlyMain
          branchPattern: ''
          scanUpto: 0
    - name: team-level-github-project
      scanType: sourceScan
      platform: github
      accountName: test-all (default)
      teamName: default
      scanLevel: repoLevel
      organisation: OpsMx
      type: organisation
      projectConfigs:
        - repository: supplychain-api
          scheduleTime: 0
          branch:
            - onlyMain
          branchPattern: ''
          scanUpto: 0

    
