apiVersion: v1
kind: ConfigMap
metadata:
  name: adhoc-project-cm
data:
  project.yaml: |
    - name: team-project
      scanType: sourceScan
      platform: github
      accountName: test-gh
      teamId: ''
      scanLevel: repoLevel
      organisation: AswathyAsokan-opsmx
      type: user
      projectConfigs:
        - repository: snyk-test
          scheduleTime: 0
          branch:
            - onlyMain
          branchPattern: ''
          scanUpto: 0
    - name: team-project
      scanType: sourceScan
      platform: github
      accountName: test-all (default)
      teamName: default
      scanLevel: repoLevel
      organisation: OpsMx
      type: organisation
      projectConfigs:
        - repository: supplychain-api
          scheduleTime: 0
          branch:
            - onlyMain
          branchPattern: ''
          scanUpto: 0
    - name: gitlab-org-project
      scanType: sourceScan
      platform: gitlab-server
      accountName: gitlab-server
      scanLevel: orgLevel
      organisation: dev
      type: ''
      projectConfigs:
        - repository: all
          scheduleTime: 0
          branch:
            - all
          branchPattern: ''
          scanUpto: 5
